apiVersion: constraints.gatekeeper.sh/v1beta1
kind: Volume-Types
metadata:
  name: volume-types
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
  parameters:
    volumes:
    # - "*" # * may be used to allow all volume types
    - configMap
    - projected
    - secret
    - downwardAPI
